# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171008_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='operation_id',
            new_name='operation',
        ),
    ]
